---
- name: install nginx-plus
  apt: name=nginx-plus state=present
  tags:
    - nginx
    - nginx-install

- name: generate nginx core config
  template: src=nginx.conf.j2 dest={{ nginx_config_d }}/nginx.conf
  register: nginx.core

- name: generate nginx http frontend config
  template: src=http.conf.j2 dest={{ nginx_config_d }}/{{ item.key }}.conf
  with_dict: vips
  register: nginx.frontend
  tags:
    - nginx-frontend
    - nginx

- name: generate monitoring config
  template: src=monitoring.j2 dest={{ nginx_config_d }}/{{ item.key }}.mon
  with_dict: probes

- name: generate nginx backend config
  template: src=upstream.sfarm.j2 dest={{ nginx_config_d }}/{{ item.key }}.sfarm
  with_dict: upstreams
  register: nginx.upstream
  tags:
    - nginx-backend
    - nginx
