---
- name: fetching pf.conf
  subversion: repo={{ svnurl }}{{ svnpath }} dest={{ checkoutpath }} username={{ svnuser }} password={{ svnpass }}
  tags:
    - deploy-pf
    - deploy-pf-q
  register: svn


- name: verifying packetfilter config
  command: /sbin/pfctl -nf {{ checkoutpath }}/pf.conf
  register: pfctl_command_result_parse
  when: svn|changed
  failed_when: "'syntax error' in pfctl_command_result_parse.stderr"
  ignore_errors: true
  tags:
    - deploy-pf
    - deploy-pf-q


- name: deploying packetfilter config
  command: /sbin/pfctl -f {{ checkoutpath }}/pf.conf
  when: pfctl_command_result_parse|success
  register: pfctl_command_result_deploy
  failed_when: "'syntax error' in pfctl_command_result_deploy.stderr"
  ignore_errors: true
  tags:
    - deploy-pf
    - deploy-pf-q


- hipchat: token={{ hipchat_token }} room={{ hipchat_room }} api={{ hipchat_api }} from="{{ inventory_hostname }}" msg="I just failed to parse pf.conf successfully, bailing out" validate_certs=no color=red
  when: (pfctl_command_result_deploy|failed or pfctl_command_result_parse|failed)
  ignore_errors: yes
  tags:
    - deploy-pf
   

- hipchat: token={{ hipchat_token }} room={{ hipchat_room }} api={{ hipchat_api }} from="{{ inventory_hostname  }}" msg="I just deployed a new pf.conf successfully, and it went ok" validate_certs=no color=green
  when: (pfctl_command_result_deploy|success and pfctl_command_result_parse|success)
  ignore_errors: yes
  tags:
    - deploy-pf
  
