---
- name: fetching pf.conf
  subversion: repo={{ svnurl }}{{ svnpath }} dest={{ checkoutpath }} username={{ svnuser }} password={{ svnpass }}
  ignore_errors: true
  tags:
    - deploy-pf
  register: svn

- name: verifying packetfilter config
  command: /sbin/pfctl -nf {{ checkoutpath }}/pf.conf
  when: svn|changed
  register: pfctl_command_result_parse
  failed_when: "'syntax error' in pfctl_command_result_parse.stderr"
  ignore_errors: true
  tags:
    - deploy-pf

- name: deploying packetfilter config
  when: (pfctl_command_result_parse|success and svn|changed)
  command: /sbin/pfctl -f {{ checkoutpath }}/pf.conf
  register: pfctl_command_result_deploy
  failed_when: "'syntax error' in pfctl_command_result_deploy.stderr"
  ignore_errors: true
  tags:
    - deploy-pf

- hipchat: token={{ hipchat_token }} room='{{ hipchat_room }}' api={{ hipchat_api }} from="pf-deploy" msg='{{ inventory_hostname }} ({{ ansible_env.SUDO_USER }}){{':' }} Fail, new pf.conf did not deploy. {{ pfctl_command_result_parse.stderr }}' validate_certs=no color=red
  when: (pfctl_command_result_deploy|failed or pfctl_command_result_parse|failed) and svn|changed
  ignore_errors: yes
  no_log: True
  tags:
    - deploy-pf

- hipchat: token={{ hipchat_token }} room='{{ hipchat_room }}' api={{ hipchat_api }} from="pf-deploy" msg='{{ inventory_hostname }} ({{ ansible_env.SUDO_USER }}){{':'}} Success, new pf.conf deployed.' validate_certs=no color=green
  when: (pfctl_command_result_deploy|success and pfctl_command_result_parse|success) and svn|changed
  ignore_errors: yes
  no_log: True
  tags:
    - deploy-pf
